import {useMemo,useState} from 'react'; import {Plus,Search,Pencil,Trash2,Users,UserCheck,UserX,Download,X} from 'lucide-react';
type Member={id:string;name:string;role:string;level:string;project:string;manager:string;location:string;email:string;skills:string;status:'Active'|'On Leave'|'Exited';joiningDate:string;shift:string};
const seed:Member[]=[
{id:'1',name:'Team Member 1',role:'Dynatrace Engineer',level:'Senior',project:'Axis Bank',manager:'Team Lead',location:'Mumbai',email:'',skills:'Dynatrace, DQL, SRE',status:'Active',joiningDate:'',shift:'General'},
{id:'2',name:'Team Member 2',role:'Dynatrace Engineer',level:'Senior',project:'Axis Bank',manager:'Team Lead',location:'Mumbai',email:'',skills:'Dynatrace, Kubernetes',status:'Active',joiningDate:'',shift:'General'},
{id:'3',name:'Team Member 3',role:'Dynatrace Engineer',level:'Junior',project:'Axis Bank',manager:'Team Lead',location:'Mumbai',email:'',skills:'Dynatrace, Linux',status:'Active',joiningDate:'',shift:'General'}];
const blank={name:'',role:'',level:'',project:'Axis Bank',manager:'',location:'Mumbai',email:'',skills:'',status:'Active' as const,joiningDate:'',shift:'General'};
export default function App(){
const[members,setMembers]=useState<Member[]>(()=>{try{return JSON.parse(localStorage.getItem('dynatrace-team-roster')||'null')||seed}catch{return seed}});
const[q,setQ]=useState(''),[filter,setFilter]=useState('All'),[open,setOpen]=useState(false),[editing,setEditing]=useState<Member|null>(null),[form,setForm]=useState<any>(blank);
const persist=(x:Member[])=>{setMembers(x);localStorage.setItem('dynatrace-team-roster',JSON.stringify(x))};
const filtered=useMemo(()=>members.filter(m=>Object.values(m).join(' ').toLowerCase().includes(q.toLowerCase())&&(filter==='All'||m.status===filter)),[members,q,filter]);
const edit=(m:Member)=>{setEditing(m);setForm({...m});setOpen(true)}; const add=()=>{setEditing(null);setForm({...blank});setOpen(true)};
const save=()=>{if(!form.name.trim())return;persist(editing?members.map(m=>m.id===editing.id?{...form,id:editing.id}:m):[...members,{...form,id:crypto.randomUUID()}]);setOpen(false)};
const remove=(id:string)=>{if(confirm('Remove this team member from the roster?'))persist(members.filter(m=>m.id!==id))};
const exportCsv=()=>{const h=['name','role','level','project','manager','location','email','skills','status','joiningDate','shift'];const csv=[h.join(','),...members.map(m=>h.map(k=>JSON.stringify((m as any)[k]??'')).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='dynatrace-team-roster.csv';a.click()};
const active=members.filter(m=>m.status==='Active').length,leave=members.filter(m=>m.status==='On Leave').length,exited=members.filter(m=>m.status==='Exited').length;
return <div className="shell"><header className="topbar"><div><div className="brand">Dynatrace Team Roster</div><div className="sub">Axis Bank • Dynatrace Operations</div></div><div className="actions"><button className="secondary" onClick={exportCsv}><Download size={16}/>Export</button><button onClick={add}><Plus size={17}/>Add Member</button></div></header>
<main><section className="hero"><div><h1>Team roster</h1><p>Maintain ownership, roles, skills, shifts and availability in one place.</p></div><div className="last">MVP • Browser-persisted roster</div></section>
<section className="cards"><div className="card"><Users/><div><span>Total Members</span><strong>{members.length}</strong></div></div><div className="card"><UserCheck/><div><span>Active</span><strong>{active}</strong></div></div><div className="card"><UserX/><div><span>On Leave</span><strong>{leave}</strong></div></div><div className="card"><UserX/><div><span>Exited</span><strong>{exited}</strong></div></div></section>
<section className="panel"><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search name, role, skill, project..." value={q} onChange={e=>setQ(e.target.value)}/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Active</option><option>On Leave</option><option>Exited</option></select></div>
<div className="tablewrap"><table><thead><tr><th>Member</th><th>Role / Level</th><th>Project</th><th>Manager</th><th>Location</th><th>Skills</th><th>Status</th><th>Shift</th><th></th></tr></thead><tbody>{filtered.map(m=><tr key={m.id}><td><b>{m.name}</b><small>{m.email||'No email added'}</small></td><td>{m.role}<small>{m.level}</small></td><td>{m.project}</td><td>{m.manager||'—'}</td><td>{m.location}</td><td>{m.skills||'—'}</td><td><span className={'pill '+m.status.toLowerCase().replace(' ','-')}>{m.status}</span></td><td>{m.shift}</td><td className="rowactions"><button className="icon" onClick={()=>edit(m)}><Pencil size={15}/></button><button className="icon danger" onClick={()=>remove(m.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No team members match the current filters.</div>}</div></section></main>
{open&&<div className="overlay"><div className="modal"><div className="modalhead"><h2>{editing?'Edit team member':'Add team member'}</h2><button className="icon" onClick={()=>setOpen(false)}><X/></button></div><div className="form">{(['name','role','level','project','manager','location','email','skills','joiningDate','shift'] as const).map(k=><label key={k}>{k==='joiningDate'?'Joining Date':k.charAt(0).toUpperCase()+k.slice(1)}<input type={k==='joiningDate'?'date':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Active</option><option>On Leave</option><option>Exited</option></select></label></div><div className="modalfoot"><button className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button onClick={save}>{editing?'Save Changes':'Add Member'}</button></div></div></div>}</div>}